secrets:
    sops:
        age_key: ENC[AES256_GCM,data:c9DfonziUhtobGc6iKQri8Nzq6fpQv5akOJpDUR9l4MiNv5++6YHtiU5tg1wLh9fRJoTfYPK0L82v5ukRil00BNqZb29LZq0gb1GEDx7osUaeDZcYNIYrDg0VLEocrTgq7UMn856myz37P1mxj8nTsYhugEmXWZYm3GL0Eg5l0t0G4xv7ozvZZ71v4lrEbyD5lujuESBldpFwzYX4JmN6KMYduOQOMusSpjokkvTZ4KYzrvV6H1n7O+do07I,iv:Bd5+fyc1gRy9lD2O1IhMHaC1jzD4RClqMtyNoa2LkOE=,tag:6RZBhvQFkS/7U4/POJT/Pg==,type:str]
        registry:
            hostname: ENC[AES256_GCM,data:ActjG8U4WRS8vFkj6mpMLknYr2q6JcBNBA==,iv:IZ4UFvFjOHXolGZWBda4nDgQf4Foo4kfc3rnM7dERcQ=,tag:1T42jOE/YCVW1o+owHJSrw==,type:str]
            username: ENC[AES256_GCM,data:pBm/ZK3emNLAL35SR3KXKvw=,iv:j8dAvjLvi5hQ672/hfKakYDnL9+L1F6XRkJydPfnLWw=,tag:voyir5C6tAN3SeF0yFj7Yg==,type:str]
            password: ENC[AES256_GCM,data:ykumR4e+xtnOnXt8zw==,iv:cxXjrJ+cbJnWFvAqrI1MSRiqacXsHwOElawTPvx+pEk=,tag:ggTUxXeF2EQI7PbZKI51uA==,type:str]
        git:
            basic_auth:
                username: ENC[AES256_GCM,data:uNnYtRWGc6ec7RvR83o=,iv:c4EWQNwYiNj7SHD+sqhPD11zhajJS0hANLu2dWQwsyA=,tag:eZzwSNH5XLvdUKP/Tvedpw==,type:str]
                #ENC[AES256_GCM,data:XnGyLvM+fvyfey5TDRr+2qjVrhuwLTKtCmaqiDZPHen5eerqJRFnYJ4O5zsFSzl0HMy6LA==,iv:USSN8JetGFx+5KhEr9eWwLaWsY2JmYjEawWaeP9hUi4=,tag:W8rcs2GlTdxvPPO2ePla4A==,type:comment]
                password: ENC[AES256_GCM,data:hkOc9sPP22PNMJidf/NiSM6bMkv71JjGoBlyVkBEJ+Tt1fT4ke+B0Q==,iv:VU8AikwK2G6FW+5D1Ji2+mJfzFEVxCE9G5W6n+t05yY=,tag:oJZUh9INNlQH0MoN3z8qew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u74ps32m3mcvd6zjaw8w2p3wwfucz0r2rxrsxmq8ldlyv5lapgkqle505u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUnlMR3czelEwUXJzK040
            RDN3eWdEREFQN215K054bGFscFNMTkdqU3g0CnJFbDRwcmxHamVndkxraVNaYnFQ
            bmhXOEpSa2NqSHBpU1pIUVNCcWxzQkEKLS0tIFlEOERJU1Jnd3ZnZSt0SzZZejhD
            bGg5VGVoNlkxUVJYU25QaktGYXUzVkkKO8UMFDYkPAGXJnLOOAYDHCT01jHMnPoO
            JFx9whlCsbD3DW0qnCDTg9vieMbKdfsXNZJwcbWtKY078+OuYcy9cQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-07T13:33:58Z"
    mac: ENC[AES256_GCM,data:4+UtFNpoHPZxjPehLFxf35JbZfMjdT7d1WLAubbx6jmwe90gx5YfyZU9PMwRrUBBqMzFXs4fO759UTn6Hj6TK35aQoXZtkgKbVMm1jyv2OaVch4SmzugWyrzc7ncODckjDwHEPKfHIMEzgOv7S9668mm4+O01gzxof34kfyEyzk=,iv:mhmiACFSBj68hNz/Sq5zcNTq4Aq9l4oieFXpyhkT0U8=,tag:fQRNYRkAU3/Ic/FUKPelHQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
