apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: tg
    apps.tanzu.vmware.com/workload-type: web
  name: tg
  namespace: default
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  env:
    - name: message
      value: tg
  source:
    git:
      ref:
        branch: main
      url: https://github.com/tfynes-pivotal/tdemo1