apiVersion: v1
kind: Service
metadata:
  name: customer-profile-x
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    carto.run/workload-name: customer-profile
  sessionAffinity: None
  type: ClusterIP