tap_install:
    sensitive_values:
        shared:
            image_registry:
                project_path: ENC[AES256_GCM,data:vVq/oJrnw64377vkGCJCJmmNJHM=,iv:OxUeyEVXpn9mtY0uVxdydQqoB/yyrxK8G9xK1cFQ9Fw=,tag:NkiYpshoU/WVyycOliYaew==,type:str]
                username: ENC[AES256_GCM,data:0+/RlQu9,iv:Jp32Z+I+XweatLPK/zDP8iwr+uApXV4sBIqGRpgUxs0=,tag:dbgB/wXbXydXzEUfUn3Ruw==,type:str]
                password: ENC[AES256_GCM,data:0i9v6eTx6+kiyRpCH/AuZNn4vDzMDsOfBsymZ7bYMFpLRiL4,iv:o3tbFdnbRD9VJIP0jApzIrM3MRZQfsqhTJm4cn/MOpk=,tag:pxeQ/IkeQi1JaTDP/qgaQg==,type:str]
        tap_gui:
            app_config:
                integrations:
                    github:
                        - host: ENC[AES256_GCM,data:nNOfI/qcuvbM2Q==,iv:TxP4CxVEvptL8WgJnLk12KFVUsoW05Rl4/Pk7st++b0=,tag:z8+Gxs0Qzhm5nh4ehiE41Q==,type:str]
                          token: ENC[AES256_GCM,data:Is5a3pBqBzHffha5gU3ARslU86/0Sm2xIZQxM++sjXb9MKq8/1TDGQ==,iv:6KLO3txmMNhfpYaYUUWSnoBGB3h8V0lfMEwxyxVM1yY=,tag:TSZq+cvyv3jLKCsmk3O96w==,type:str]
                auth:
                    environment: ENC[AES256_GCM,data:AQSkKn5cwDN5YEs=,iv:ucR8rZLkQwsnzRDkKjtNYrknRjhvh5RzbLj5jL+lzac=,tag:pm1fy7Sp5Id5pr+I4tPorg==,type:str]
                    providers:
                        github:
                            development:
                                clientId: ENC[AES256_GCM,data:nqCwW7yZR+WNw/6QHCR3mZL8OZM=,iv:kU/VX2sZ3qqIOddKvM/0dHAG/+0CFkzoPydPhY3R/6w=,tag:7bf4CN8JUSfeXl0/mZ9MSw==,type:str]
                                clientSecret: ENC[AES256_GCM,data:7CNw94Xb4mDorNbQKWkIirb/3BjYKcpBlXNuimdlP2lcqmdv4rJnqg==,iv:AV9TZtCuXgOKFVpIWT0/wev9satGsP/Hdy9Fk72GFUk=,tag:Un7q2gMRxfFh5GZI3H5otQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u74ps32m3mcvd6zjaw8w2p3wwfucz0r2rxrsxmq8ldlyv5lapgkqle505u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSDJlSXE1VmxxakJOaDI5
            UHJKemNKQWNMM1NCYjNJRFNtUS9seTF0Nlg4CkVKK2FWK2tzRnBxVGpuaW5tc1hK
            SG1pNW5tVHJLL0c4RHEzYnJtU2xTRU0KLS0tIEsxQkRGOVFHcWQwTEN4eWxVMEtm
            S3dXNDBhVXVtQjlLeG9vNWhhYkpBZ1UKPJDVLUigjcJEdSThXLc/yEOXxI7qSRJV
            PPzXWf2JIfJjbVXbdM3nfanlPSSyQZcUCTr+pfJPL4ri7Y+sNm/48Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-31T19:04:19Z"
    mac: ENC[AES256_GCM,data:GHJ70TDzp8AZt0XQLdZVnQerYlrxV3Xxt8/NeaZSYomrs5dHuS0RRoawCAsJLR190ph/u2D9NP63xWH7aKI0CJtYlKqCgASA+XJ2L9fhI1E2QoJt+pOqVlVMICYG5G17ZMuSNDGLlk+YQHjMbiP3oR38B8OPvUrWHzrwOAde8C0=,iv:w+HpCOu20MA/4h089GqW1Xvq36VIc77JsRScZdFhPCw=,tag:O8J4oGVL8Tn6zH3DpHjCaQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
