tap_install:
    sensitive_values:
        shared:
            image_registry:
                project_path: ENC[AES256_GCM,data:vVq/oJrnw64377vkGCJCJmmNJHM=,iv:OxUeyEVXpn9mtY0uVxdydQqoB/yyrxK8G9xK1cFQ9Fw=,tag:NkiYpshoU/WVyycOliYaew==,type:str]
                username: ENC[AES256_GCM,data:0+/RlQu9,iv:Jp32Z+I+XweatLPK/zDP8iwr+uApXV4sBIqGRpgUxs0=,tag:dbgB/wXbXydXzEUfUn3Ruw==,type:str]
                password: ENC[AES256_GCM,data:0i9v6eTx6+kiyRpCH/AuZNn4vDzMDsOfBsymZ7bYMFpLRiL4,iv:o3tbFdnbRD9VJIP0jApzIrM3MRZQfsqhTJm4cn/MOpk=,tag:pxeQ/IkeQi1JaTDP/qgaQg==,type:str]
        tap_gui:
            app_config:
                auth:
                    allowGuestAccess: ENC[AES256_GCM,data:9KvTzg==,iv:pa7KmlitlS/5zLAvvccN9Q61Hy37J0jmF2ScpVUu3NE=,tag:g2CO9wQW6xEaBQDxbfIK5Q==,type:bool]
                    environment: ENC[AES256_GCM,data:72mP/vwUfK6oGAM=,iv:CWJ70Hs2cBqqLSdXouKo/3lSZ7eVRuV0IWSbpKGaU7Y=,tag:J1aDoZa6EVssHXtUxBopRA==,type:str]
                    providers:
                        github:
                            development:
                                clientId: ENC[AES256_GCM,data:A6mR9pvbz045gQfoQ/OUHQoWvN8=,iv:OlHY5ZEnnYKTCVkT8OcB68QEi3eFx6W9vFXjc+WF1Pk=,tag:Jvp04Iu/0tQDWlp7rzfpvA==,type:str]
                                clientSecret: ENC[AES256_GCM,data:+nVy8ZuW1/k3Rv/N+ykoNbJbw/QZOJrmA2P65NCppeV7kiK5DQcYBg==,iv:aJxP7tLSA57fO+q6BDjyPkH/FT4pEtViIG1+GU5cKrk=,tag:+4CrW19sHQqxU5l6xpM9Vw==,type:str]
                integrations:
                    github:
                        - host: ENC[AES256_GCM,data:F38eOWzitj3Jcw==,iv:DueTArhDjZeUAHnCRe3MOabUGu47S5UUGDWoQdolB7E=,tag:VqYxRrtoxW07qNPJseEMVg==,type:str]
                          token: ENC[AES256_GCM,data:7VrV0nGdSvFZBD4DcwcznJqMx6/kTBJyG2AjfI4wBOC/GlKj6EJiUQ==,iv:49UL2mWAokI/PVFIU8UZCRSz6fcyO9Mczya7H7VKo/8=,tag:+q4HKCy/VG7Jp+FHGAP6LQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u74ps32m3mcvd6zjaw8w2p3wwfucz0r2rxrsxmq8ldlyv5lapgkqle505u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSDJlSXE1VmxxakJOaDI5
            UHJKemNKQWNMM1NCYjNJRFNtUS9seTF0Nlg4CkVKK2FWK2tzRnBxVGpuaW5tc1hK
            SG1pNW5tVHJLL0c4RHEzYnJtU2xTRU0KLS0tIEsxQkRGOVFHcWQwTEN4eWxVMEtm
            S3dXNDBhVXVtQjlLeG9vNWhhYkpBZ1UKPJDVLUigjcJEdSThXLc/yEOXxI7qSRJV
            PPzXWf2JIfJjbVXbdM3nfanlPSSyQZcUCTr+pfJPL4ri7Y+sNm/48Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-04T20:29:39Z"
    mac: ENC[AES256_GCM,data:E9G1HX2Bxat26ND8t+fYkdUINfubc9bdG5DIqjban5hCbjOEdkklgDaJmb7NHDj1SF6DHZMgy6r60EcUL67WeUb83XmZbDbub+TJ7izT3u34Ae6exL8GoEEVMuEPLBCXkrNkOmouyzhXFY9avhn9tJrivZlNetK47bhHItO/9OI=,iv:ijzHXeRHHxqKYErxjFZC1WtYsJo5/F/H3Y9a9MZEcxA=,tag:hoB05MeKBqgXOLZVQAYK7Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
