apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-petclinic-protected
  namespace: default
  labels:
    #!apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: petclinic
    #! networking.knative.dev/visibility: cluster-local
spec:
  build:
    env:
    - name: BP_GRADLE_BUILD_FILE
      value: skip
    - name: BP_JVM_VERSION
      value: "17"
  env:
  - name: SPRING_PROFILES_ACTIVE
    value: postgres
  - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK
    value: TRACE
  - name: forward-headers-strategy
    value: FRAMEWORK
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/min-scale: "1"
  source:
    git:
      url: https://github.com/spring-projects/spring-petclinic
      ref:
        branch: main
  serviceClaims:
    - name: postgres-db
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: postgres1-claim
