#@ load("@ytt:data", "data")
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: tanzu-sync-secrets
  namespace: tanzu-sync
  annotations:
    kapp.k14s.io/change-group: eso/secretstore
    kapp.k14s.io/change-rule.0: "upsert after upserting eso/install"
    kapp.k14s.io/change-rule.1: "delete before deleting eso/install"
spec:
  provider:
    vault:
      server: #@ data.values.secrets.eso.vault.server
      path: #@ data.values.secrets.eso.vault.path
      version: #@ data.values.secrets.eso.vault.version
      namespace: #@ data.values.secrets.eso.vault.namespace
      auth:
        kubernetes:
          mountPath: #@ data.values.secrets.eso.vault.auth.kubernetes.mountPath
          role: #@ data.values.secrets.eso.vault.auth.kubernetes.role
          serviceAccountRef:
            name: "tanzu-sync-vault-sa"