apiVersion: v1
kind: Secret
metadata:
  name: api-portal-cm-tls-overlay-secret
  namespace: tap-install
stringData:
  patch.yml: |
    #@ load("@ytt:overlay", "overlay")
    #@ theType = overlay.subset({"kind":"HTTPProxy"})
    #@ theName =  overlay.subset({"metadata":{"name":"api-portal"}})
    #@overlay/match by=overlay.and_op(theType, theName), expects="0+"
    ---
    spec:
      virtualhost:
          #@overlay/match missing_ok=True
          tls:
            secretName: api-portal-tls-cert