#@ load("@ytt:overlay", "overlay")

apiVersion: v1
kind: Secret
metadata:
  name: reqfix-overlay-secret
  namespace: tap-install
stringData:
  patch.yml: |
    #@ load("@ytt:overlay", "overlay")
    #@ deployments = overlay.subset({"kind":"Deployment"})
    #@ daemonsets =  overlay.subset({"kind":"DaemonSet"})
    #@overlay/match by=overlay.or_op(deployments, daemonsets), expects="0+"
    ---
    spec:
      template:
        spec:
          containers: 
          #@overlay/match by=overlay.all, expects="0+" 
          -
            #@overlay/match missing_ok=True 
            #@overlay/remove
            resources:
