apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: tdemo1
    apps.tanzu.vmware.com/workload-type: web
    networking.knative.dev/visibility: cluster-local
  name: tdemo1
  namespace: default
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  env:
    - name: message
      value: tanzu1
  source:
    git:
      ref:
        branch: main
      url: https://github.com/tfynes-pivotal/tdemo1