apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tdemo-python1
  namespace: default
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tdemo-python1
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/tfynes-pivotal/tdemo-python1
      ref:
        branch: main
  build:
    env:
      - name: BP_FUNCTION
        value: func.test
