apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: tdemo-global
    apps.tanzu.vmware.com/workload-type: web
  name: tdemo-global2
  namespace: default
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  env:
    - name: message
      value: tanzu-global2
  source:
    git:
      ref:
        branch: main
      url: https://github.com/tfynes-pivotal/tdemo1