apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: weatherforecaster
  namespace: default
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: weatherforecaster
    networking.knative.dev/visibility: cluster-local
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      ref: 
        branch: main
      url: https://github.com/tfynes-pivotal/weatherforecaster
