apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: petclinic-gateway
  namespace: default
spec:
  routes:
    - conditions:
      - prefix: /
      services: 
        - name: petclinic-gateway
          port: 80
  virtualhost:
    fqdn: petclinic.tkglab.h2o-4-11809.h2o.vmware.com
    tls:
      secretName: petclinic-gateway-tls-cert