apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tdemo-gateway-cert
  namespace: default
spec:
  dnsNames:
  - tdemo.tkglab.h2o-4-11809.h2o.vmware.com
  secretName: tdemo-gateway-tls-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer