apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: tdemo-gateway
  namespace: default
spec:
  routes:
    - conditions:
      - prefix: /
      services: 
        - name: tdemo-gateway
          port: 80
  virtualhost:
    fqdn: tdemo.tkglab.h2o-4-11809.h2o.vmware.com
    tls:
      secretName: tdemo-gateway-tls-cert