apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tdemo-gateway-cert
  namespace: default
spec:
  dnsNames:
  - tdemo.ekslab2.tap.fynesy.com
  secretName: tdemo-gateway-tls-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer