#@ load("@ytt:data", "data")
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  annotations:
    kapp.k14s.io/change-group: cert-manager/cluster-issuer
    kapp.k14s.io/change-rule: "upsert after upserting cert-manager"
spec:
  acme:
    email: tmfynes@yahoo.com
    privateKeySecretRef:
      name: letsencrypt-production
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: contour
            podTemplate:
              spec:
                serviceAccountName: cm-sa

