#@ load("@ytt:data", "data")

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: scg-operator
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: scg-operator
    kapp.k14s.io/change-rule.0: "upsert after upserting scg-repo"
    kapp.k14s.io/change-rule.1: "upsert after upserting cert-manager"
    kapp.k14s.io/change-rule.2: "upsert after upserting tap"
spec:
  packageRef:
    refName: spring-cloud-gateway.tanzu.vmware.com
    versionSelection:
      constraints: 2.0.6
      prereleases: {}
  serviceAccountName: tap-install-sa
  values:
  - secretRef:
      name: tanzu-registry