#@ load("@ytt:data", "data")
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: scg
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: scg-repo
spec:
  fetch:
    imgpkgBundle:
      image: "registry.tanzu.vmware.com/spring-cloud-gateway-for-kubernetes/scg-package-repository:2.0.3"
      #!secretRef:
        #!name: install-registry-dockerconfig