apiVersion: ENC[AES256_GCM,data:ikg=,iv:JYbCb5L/J7ioJiEF+iKAwjYvzVAihrYGXLj2RG7vBog=,tag:93kVzRrYOETbXSgo8MuTZw==,type:str]
data:
    client-id: ENC[AES256_GCM,data:B9ERHl9eqhg4lI8/XiF2J4ScUzXoM0/up3CeGw==,iv:773c9W2QhPL1Qyq4bC9ZEGgMe1GrYnzqjOYCIBEYrXc=,tag:1BwgK1xGLQgdQOA0HEZQtA==,type:str]
    client-secret: ENC[AES256_GCM,data:2ELfPDtrnF0h9sl8IN0dgxPzRLT5go/eTlJm23hY1pY/WTac9Dz1pagQbCCwXaxGFNt5/pL9dEs=,iv:FPgUf20kIjm5qojBYqeX6WFx0V/ZZlEzfZaImplkKZo=,tag:+Nbm/NT+Rct2z81EjIz2YQ==,type:str]
    issuer-uri: ENC[AES256_GCM,data:5r8vnProBlUKtMND/KFn0/O/6eJ3wS+tMVhgvpppPa1FalFiAarPxRtdLPyGkNJWFpjv07HEO6Y4BXxPNtJvYz20hV07ap2c3qLoNQ==,iv:qlglTxAIsF7Ynueu08L+2S3q40Mdr4zABJag2rJKUGE=,tag:uwdd5QBnC3v7ZjkPsy/oWA==,type:str]
    scope: ENC[AES256_GCM,data:unSKJ7aZV+klzsi4JZPF0WUzkrmFhQnvR4SWzTcqSWR/pU1rlLtNn2oC3U0=,iv:7t0WVMyFVhIn/ji/jqLcOcQSvNdTxVStUKaADZBLU3A=,tag:r1+daUttCL0nae2OWkfPTQ==,type:str]
    user-name-attribute: ENC[AES256_GCM,data:VoZwH+OKtx52ZoeM,iv:zgMqKZ58xpkhb8JFRvuAzIenfsoRBuUp4KIGC+pIChQ=,tag:t8LoYSApSR8YLSFd7zoz/g==,type:str]
kind: ENC[AES256_GCM,data:pY64xiuR,iv:R3l2zu7CD2oGtD43UqBhrHodhuS+2hw+CzD+nOp5aHI=,tag:LYqzpvotkZod80Nt9cVlgg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kHwRKMEVAg24tXzCuseO,iv:CVB4mwU3uz4SDyQRPZPVLFxuIqtL+p9Weqbeh0XmAbM=,tag:aongvazwo6HK0SOWjIsBcQ==,type:str]
    namespace: ENC[AES256_GCM,data:i/Cgrst0DCq11w==,iv:DzeRRSPrQHK2/p364ulzztOXQ+2S+tz5a/69Qxa2NsU=,tag:vwxmwZhU5huYrnZDKZkR1w==,type:str]
type: ENC[AES256_GCM,data:Ti0I0poa,iv:KTGsqcSqm1g5uwPOi0FAKX7xKC6aymJmuMC9SdcDjuY=,tag:EsTOui2Gjz9bij1UYSqbeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u74ps32m3mcvd6zjaw8w2p3wwfucz0r2rxrsxmq8ldlyv5lapgkqle505u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRmdDWFdwek5KdXA0TU1w
            RE1aNFVXdHJYNmNnbWM4YlRLL1FsT3MrMWpNClN0ODB1ODRwUU9jT3p0c1ZLTFpR
            WDJRSDBRWm1sd0FNOWdJTnQwNjlFRVUKLS0tIDcrVmtIR3QrLy9tczJJdU5VZlhr
            bmxUTVBaYTlIVTZ5RmJMSnVVSmZJWGsKLzTdZgrcz5DbHCHQ8tRM47V55DHSu4eO
            psRD2qyiy2mMyk0QSD4CF+WzgOTBXiT797+OMVuNuZItuXIMqJmpRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-25T18:55:01Z"
    mac: ENC[AES256_GCM,data:7XESVrsGwM3qGXxeAmrfrNP9y1V+ViUn6mYVgA9wt3g3t+5E6jJroffQzMU2lWq4lIAbKO6roPr15jJL9hQE8v3bTmaqh/361rnmxsDdLOxpjpyxij0baX3bVuqhlmopGxP0RPZHiMAPMY8HBLTQ4LJUuxXqsG+HjZqcb7ItveI=,iv:zQfh7re8qxQHbAhHEVFB/wg2aqDWXNRjQaRq2ub9A0w=,tag:GfhvNwtFHV8qA1Mu6XQ0JA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
