apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-portal-tls-cert.yaml
  namespace: api-portal
spec:
  dnsNames:
  - api-portal.tkglab.h2o-4-11809.h2o.vmware.com
  secretName: api-portal-tls-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer